### ISSUE TITLE
json bug

### ISSUE THREAD

**Issue by Positive2022** [HisRoyalBaguettes/clever-chat-v7#1]
rror: Ran into an Error. FetchError: invalid json response body at https://noideawhatthisis.hisroyal123.repl.co/?message=Live&gender=Male&name=Droid&developer_name=Positive%20from%20Omniverse%20Development&user=Droid&age=0.6&birthday=10%20April%202021&birthplace=Cloud&birthyear=2021&religion=Bot&favouriteactor=Sallu%20Bhai&favouriteactress=Your%20Mom&favouriteauthor=James%20Bond&favouriteband=Imagine&favouritebook=Diary&celebrity=Sallu%20Bhai&chinesesign=Dragon&family=Chatterbox&etype=Chatter%20Box&ethics=The%20silver%20rule&favouritecolor=Xanthic&favouritefood=eletricity&favouritemovie=Matrix&favouriteopera=Carmen&favouriteseason=Spring&favouriteshow=Discovery&song=Heavy%20Driver%20-%20NAZZ&favouritesubject=Chatting&favouritefootballteam=uh reason: Unexpected token < in JSON at position 0
    at /home/container/node_modules/clever-chat/src/chatbot.js:82:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Chatbot.chat (/home/container/node_modules/clever-chat/src/chatbot.js:81:22)
    at async Object.run (/home/container/utils/aichat.js:25:21)
    at async module.exports (/home/container/events/message.js:16:9)

**Comment by hisRoyalty** [comment]
Problem with acobot :)
