### ISSUE TITLE
add emojis

### ISSUE THREAD

**Issue by Positive2022** [HisRoyalBaguettes/clever-chat-v7#2]
it should send random emojis that user passes as an array in chatbot client options

**Comment by hisRoyalty** [comment]
Emojis? As in?

**Comment by hisRoyalty** [comment]
@Positive2022 , please let us know what you mean by this, thanks.

**Comment by Positive2022** [comment]
For example when a user sends emojis, it should also reply with random emojis,

It should also be able to send emojis with normal text message which makes it appealing

**Comment by hisRoyalty** [comment]
Hi @Positive2022 ,

Not sure if that’ll be possible, since this package is NOT based on Discord, and is an all-rounder.


Thanks,
Royalty
